// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import {application} from "./application"

import AutoExpandTextAreaController from "./auto_expand_text_area_controller"
import CounterInputController from "./counter_input_controller"
import DarkModeController from "./dark_mode_controller"
import DateRangePickerController from "./date_range_picker_controller"
import DropdownController from "./dropdown_controller"
import GalleryController from "./gallery_controller"
import HelloController from "./hello_controller"
import HelpSearchController from "./help_search_controller"
import InboxController from "./inbox_controller"
import InsightChartController from "./insight_chart_controller"
import InsightsController from "./insights_controller"
import ModalController from "./modal_controller"
import NavController from "./nav_controller"
import PricingController from "./pricing_controller"
import PropertiesController from "./properties_controller"
import ScrollSpyController from "./scroll_spy_controller"
import SearchController from "./search_controller"
import SelectAllController from "./select_all_controller"
import SmoothScrollController from "./smooth_scroll_controller"
import TabsController from "./tabs_controller"
import VisibilityController from "./visibility_controller"

application.register("auto-expand-text-area", AutoExpandTextAreaController)

application.register("counter-input", CounterInputController)

application.register("dark-mode", DarkModeController)

application.register("date-range-picker", DateRangePickerController)

application.register("dropdown", DropdownController)

application.register("gallery", GalleryController)

application.register("hello", HelloController)

application.register("help-search", HelpSearchController)

application.register("inbox", InboxController)

application.register("insight-chart", InsightChartController)

application.register("insights", InsightsController)

application.register("modal", ModalController)

application.register("nav", NavController)

application.register("pricing", PricingController)

application.register("properties", PropertiesController)

application.register("scroll-spy", ScrollSpyController)

application.register("search", SearchController)

application.register("select-all", SelectAllController)

application.register("smooth-scroll", SmoothScrollController)

application.register("tabs", TabsController)

application.register("visibility", VisibilityController)
