default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tech_publisher_development

test:
  <<: *default
  database: tech_publisher_test

production:
  <<: *default
  database: tech_publisher_production
  username: tech_publisher
  password: <%= ENV['TECH_PUBLISHER_DATABASE_PASSWORD'] %>
