
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tech_publisher_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: tech_publisher_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432

production:
  url: <%= ENV['DATABASE_URL'] %>