--- !ruby/object:Railsui::Configuration
application_name: tech_publisher
support_email: victorcorp11@gmail.com
theme: shepherd
colors:
  primary:
    '50': "#fff1f2"
    '100': "#ffe4e6"
    '200': "#fecdd3"
    '300': "#fda4af"
    '400': "#fb7185"
    '500': "#f43f5e"
    '600': "#e11d48"
    '700': "#be123c"
    '800': "#9f1239"
    '900': "#881337"
    '950': "#4c0519"
  secondary:
    '50': "#eaf6fc"
    '100': "#c1e3f7"
    '200': "#98d1f2"
    '300': "#6FBFED"
    '400': "#46ACE7"
    '500': "#1D9AE2"
    '600': "#187eb9"
    '700': "#126290"
    '800': "#0D4667"
    '900': "#082a3e"
    '950': "#030E15"
pages: [ ]
